.TH "Dexter" 3 "Sat Apr 11 2020" "Version 0.01" "Dexter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dexter
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTensor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T , std::size_t N> \fBTensor\fP< T, N > \fBentryWiseAdd\fP (const \fBTensor\fP< T, N > &lhs, const \fBTensor\fP< T, N > &rhs)"
.br
.ti -1c
.RI "template<class T , std::size_t N> \fBTensor\fP< T, N > \fBentryWiseSub\fP (const \fBTensor\fP< T, N > &lhs, const \fBTensor\fP< T, N > &rhs)"
.br
.ti -1c
.RI "template<class T , std::size_t N> \fBTensor\fP< T, N > \fBentryWiseProd\fP (const \fBTensor\fP< T, N > &lhs, const \fBTensor\fP< T, N > &rhs)"
.br
.ti -1c
.RI "template<class T , std::size_t N> \fBTensor\fP< T, N > \fBentryWiseDiv\fP (const \fBTensor\fP< T, N > &lhs, const \fBTensor\fP< T, N > &rhs)"
.br
.ti -1c
.RI "template<class T , std::size_t N> \fBTensor\fP< T, N > \fBentryWiseExp\fP (const \fBTensor\fP< T, N > &lhs, const \fBTensor\fP< T, N > &rhs)"
.br
.ti -1c
.RI "template<class T , std::size_t N> \fBTensor\fP< T, N > \fBentryWiseLog\fP (const \fBTensor\fP< T, N > &lhs, const \fBTensor\fP< T, N > &rhs)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class T , std::size_t N> \fBTensor\fP<T, N> Dexter::entryWiseAdd (const \fBTensor\fP< T, N > & lhs, const \fBTensor\fP< T, N > & rhs)"

.SS "template<class T , std::size_t N> \fBTensor\fP<T, N> Dexter::entryWiseDiv (const \fBTensor\fP< T, N > & lhs, const \fBTensor\fP< T, N > & rhs)"

.SS "template<class T , std::size_t N> \fBTensor\fP<T, N> Dexter::entryWiseExp (const \fBTensor\fP< T, N > & lhs, const \fBTensor\fP< T, N > & rhs)"

.SS "template<class T , std::size_t N> \fBTensor\fP<T, N> Dexter::entryWiseLog (const \fBTensor\fP< T, N > & lhs, const \fBTensor\fP< T, N > & rhs)"

.SS "template<class T , std::size_t N> \fBTensor\fP<T, N> Dexter::entryWiseProd (const \fBTensor\fP< T, N > & lhs, const \fBTensor\fP< T, N > & rhs)"

.SS "template<class T , std::size_t N> \fBTensor\fP<T, N> Dexter::entryWiseSub (const \fBTensor\fP< T, N > & lhs, const \fBTensor\fP< T, N > & rhs)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Dexter from the source code\&.
