.TH "Dexter/main.cxx" 3 "Sat Apr 11 2020" "Version 0.01" "Dexter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dexter/main.cxx
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include 'dxtrTensor\&.hxx'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBTest1\fP ()"
.br
.ti -1c
.RI "bool \fBTest2\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SS "bool Test1 ()"
Tests weather idtoad and adtoid work as intentioned\&. \[ a = \int^{b}_{a} f \left( t \right) dt \] 
.SS "bool Test2 ()"
Tests the speed of idtoad and adtoid\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Dexter from the source code\&.
